"""Generate Lean theorem instances for committed E-core certificates."""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUT = ROOT / "formal" / "Erdos993Formal" / "Generated" / "Ecore.lean"
LOGS = [
    ROOT / "logs" / "993_ecore_polyc_certification.json",
    ROOT / "logs" / "993_ecore_polyc_ext.json",
    ROOT / "logs" / "993_ecore_polyc_topup.json",
]


def load_instances() -> list[tuple[int, int, int]]:
    instances = set()
    for path in LOGS:
        data = json.loads(path.read_text())
        if data.get("failed"):
            raise SystemExit(f"{path.relative_to(ROOT)} contains failed certificates")
        instances.update(tuple(row) for row in data["certified"])
    return sorted(instances)


def build_record(instance: tuple[int, int, int]) -> tuple[tuple[int, int, int], dict]:
    from scripts.export_ecore_poly_certificate import build_payload

    return instance, build_payload(*instance)


def lean_list(values: Iterable[int]) -> str:
    return "[" + ", ".join(str(int(value)) for value in values) + "]"


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def theorem_block(instance: tuple[int, int, int], payload: dict) -> str:
    k, h, w = instance
    poly_name = f"ecorePoly_{k}_{h}_{w}"
    theorem_name = f"ecoreCert_{k}_{h}_{w}"
    coeffs = lean_list(payload["polynomial_coefficients_ascending"])
    bound = payload["bound"]
    scale = payload["scale_denominator"]
    return f"""
/--
E-core Taylor-shift certificate for `(k, h, w) = ({k}, {h}, {w})`.
The integer polynomial is scaled by the positive denominator `{scale}`.
-/
abbrev {poly_name} : IntPoly := {coeffs}

theorem {theorem_name} :
    ∀ n : Nat, 1 ≤ n -> 0 ≤ eval {poly_name} (Int.ofNat n) :=
  certificate_sound (p := {poly_name}) {{
    bound := {bound}
    samples := samplesNonneg_of_bool (by native_decide)
    tail := coeffsNonneg_of_bool (by native_decide)
  }}
"""


def render(records: list[tuple[tuple[int, int, int], dict]]) -> str:
    triples = ",\n".join(
        f"  ({k}, {h}, {w})" for (k, h, w), _payload in records
    )
    blocks = "\n".join(theorem_block(instance, payload) for instance, payload in records)
    return f"""-- Generated by scripts/generate_ecore_lean_certificates.py.
-- Do not edit by hand.

import Erdos993Formal.PolynomialCertificate

namespace Erdos993
namespace PolynomialCertificate
namespace GeneratedEcore

def certifiedEcoreTriples : List (Nat × Nat × Nat) := [
{triples}
]

theorem certifiedEcoreTriples_length :
    certifiedEcoreTriples.length = {len(records)} := by
  native_decide

{blocks}
end GeneratedEcore
end PolynomialCertificate
end Erdos993
"""


def generate(instances: list[tuple[int, int, int]], jobs: int) -> str:
    started = time.time()
    records: dict[tuple[int, int, int], dict] = {}
    with ProcessPoolExecutor(max_workers=jobs) as pool:
        futures = [pool.submit(build_record, instance) for instance in instances]
        for index, future in enumerate(as_completed(futures), start=1):
            instance, payload = future.result()
            records[instance] = payload
            if index == 1 or index % 50 == 0 or index == len(instances):
                elapsed = time.time() - started
                print(
                    f"generated {index}/{len(instances)} E-core Lean certificates "
                    f"({elapsed:.1f}s)",
                    file=sys.stderr,
                    flush=True,
                )
    return render([(instance, records[instance]) for instance in instances])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--jobs", type=int, default=min(16, os.cpu_count() or 1))
    parser.add_argument("--limit", type=int, help="generate only the first N instances")
    parser.add_argument("--check", action="store_true", help="compare generated Lean to --out")
    args = parser.parse_args()

    if args.jobs < 1:
        raise SystemExit("--jobs must be positive")

    instances = load_instances()
    if args.limit is not None:
        instances = instances[: args.limit]

    text = generate(instances, args.jobs)
    if args.check:
        committed = args.out.read_text()
        if text != committed:
            raise SystemExit(f"{display_path(args.out)} differs from generated output")
        print(f"{display_path(args.out)} matches generated output")
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"wrote {display_path(args.out)}")


if __name__ == "__main__":
    main()
